---
- name: Install tools on Data Science Toolbox
  hosts: local
  become: true

  tasks:
    - name: Install git
      tags: git
      package:
        name: git

    - name: Install make
      tags: make
      apt:
        pkg: make

    - name: Install csvquote
      tags: csvquote
      shell:
        chdir: /tmp
        cmd: |
          git clone https://github.com/dbro/csvquote.git && \
          cd csvquote && \
          make && \
          make install

    - name: Install bat
      tags: bat
      apt:
        # deb: https://github.com/sharkdp/bat/releases/download/v0.18.0/bat_0.18.0_arm64.deb
        deb: https://github.com/sharkdp/bat/releases/download/v0.18.0/bat_0.18.0_amd64.deb

    - name: Install dsutils
      git:
        repo: https://github.com/jeroenjanssens/dsutils.git
        dest: /usr/bin/dsutils
      tags:
        - body
        - cols
        - csv2vw
        - dseq
        - dsutils
        - header
        - pbc
        - Rio
        - scrape
        - servewd
        - trim
        - unpack

    - name: Install man
      tags: man
      apt:
        pkg: man-db

    - name: Install bc
      tags: bc
      apt:
        pkg: bc

    - name: Install htop
      tags: htop
      apt:
        pkg: htop

    - name: Install unzip
      tags: unzip
      apt:
        pkg: unzip

    - name: Install Node.JS and npm
      tags:
        - xml2json
        - fx
      apt:
        pkg:
          - nodejs
          - npm

    - name: Install xml2json
      shell: npm install -g xml2json-command

    - name: Install nano
      tags: nano
      apt:
        pkg: nano

    - name: Install sample
      pip:
        name:
          sample-stream

    - name: Install gron
      tags: gron
      apt:
        pkg: gron

    - name: Install json2csv
      tags: json2csv
      unarchive:
        src: https://github.com/jehiah/json2csv/releases/download/v1.2.1/json2csv-1.2.1.linux-amd64.go1.13.5.tar.gz
        dest: /usr/bin
        remote_src: true
        mode: +x
        extra_opts:
          - '--strip-components'
          - '1'

    - name: Install fx
      tags: fx
      shell: npm install -g fx

    - name: Install R
      tags: r
      block:
      - name: Install R
        apt:
          pkg:
            - r-base
            - r-cran-tidyverse

      - name: Install R packages from CRAN
        shell: echo "install.packages('{{item}}', repos='https://cloud.r-project.org')" | R --slave --no-save --no-restore-history
        with_items:
          - janitor
          - docopt

      - name: Install R packages from GitHub
        shell: echo "remotes::install_github('{{item}}', upgrade = 'never')" | R --slave --no-save --no-restore-history
        with_items:
          - coolbutuseless/devout
          - jeroenjanssens/miniansi
          - coolbutuseless/devoutansi
          - jeroenjanssens/rush@ansi

    - name: Install PyData
      tags: pydata
      pip:
        name:
          - numpy
          - pandas

    - name: Install requirements for scrape
      tags:
        - dsutils
        - scrape
      pip:
        name: cssselect

    - name: Install csvkit
      tags:
        - csvclean
        - csvcut
        - csvformat
        - csvgrep
        - csvjoin
        - csvjson
        - csvkit
        - csvlook
        - csvpy
        - csvsort
        - csvsql
        - csvstack
        - csvstat
        - in2csv
        - sql2csv
      apt:
        pkg: csvkit

    - name: Install parallel
      tags: parallel
      apt:
        pkg: parallel

    - name: Install curl
      tags: curl
      apt:
        pkg: curl

    - name: Install jq
      tags: jq
      apt:
        pkg: jq

    - name: Install 7zip
      tags: 7zip
      apt:
        pkg: p7zip-full

    - name: Install unrar
      tags: unrar
      apt:
        pkg: unrar-free

    - name: Install xmlstarlet
      tags: xmlstarlet
      apt:
        pkg: xmlstarlet

    - name: Install tree
      tags: tree
      apt:
        pkg: tree

    - name: Install aws
      tags: aws
      shell:
        chdir: /tmp
        warn: false
        cmd: |
          # curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

    - name: Install Vowpal Wabbit
      tags: vw
      block:
      - name: Install requirements for vw
        apt:
          pkg:
            - git
            - libboost-dev
            - libboost-program-options-dev
            - libboost-system-dev
            - libboost-thread-dev
            - libboost-math-dev
            - libboost-test-dev
            - zlib1g-dev
            - cmake
            - g++

      - name: Install requirements for vw
        shell:
          chdir: /tmp
          warn: false
          cmd: |
            curl -sL https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz > flatbuffers.tar.gz && \
            tar -xzf flatbuffers.tar.gz && \
            cd flatbuffers-* && \
            mkdir -p build && \
            cd build && \
            cmake -G "Unix Makefiles" -DFLATBUFFERS_BUILD_TESTS=Off -DFLATBUFFERS_INSTALL=On -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_FLATHASH=Off .. && \
            make install -j$(nproc) && \
            cd /tmp && \
            rm -rf flatbuffers*

      - name: Install vw
        shell:
          chdir: /tmp
          cmd: |
            git clone --recursive https://github.com/VowpalWabbit/vowpal_wabbit.git && \
            cd vowpal_wabbit && \
            make && \
            make install && \
            cd /tmp && \
            rm -rf vowpal_wabbit

    - name: Install tapkee
      tags: tapkee
      block:
      - name: Install requirements for tapkee
        apt:
          pkg:
            - libboost-dev
            - libboost-program-options-dev
            - libboost-system-dev
            - libboost-thread-dev
            - libboost-math-dev
            - libboost-test-dev
            - zlib1g-dev
            - cmake
            - g++

      - name: Install requirements for tapkee
        shell:
          chdir: /tmp
          warn: false
          cmd: |
            curl -sL https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz > eigen.tar.gz && \
            mkdir -p eigen && \
            tar -xzvf eigen.tar.gz -C eigen --strip-components=1 && \
            cd eigen && \
            mkdir -p build && cd build && cmake .. && \
            make && \
            make install && \
            cd /tmp && \
            rm -rf eigen*

      - name: Install tapkee
        shell:
          chdir: /tmp
          cmd: |
            git clone https://github.com/lisitsyn/tapkee.git && \
            cd tapkee && \
            mkdir -p build && \
            cd build && \
            cmake .. && \
            make && \
            cp -v /tmp/tapkee/bin/tapkee /usr/bin && \
            cd /tmp &&
            rm -rf tapkee

    - name: Install cowsay
      tags: cowsay
      block:
      - name: Install cowsay package
        apt:
          pkg: cowsay

      - name: Copy cowsay to /usr/bin/
        copy:
          remote_src: true
          src: /usr/games/cowsay
          dest: /usr/bin/cowsay
          mode: +x

    - name: Install xsv
      tags: xsv
      unarchive:
        src: https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
        dest: /usr/bin
        remote_src: true
        mode: +x

    - name: Install pup
      tags: pup
      unarchive:
        src: https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
        # src: https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_arm64.zip
        dest: /usr/bin
        remote_src: true
        mode: +x
