---
- name: Setup user on Data Science Toolbox
  hosts: local
  become: true

  tasks:
    - name: Create wheel group
      group:
        name: wheel
        state: present

    - name: Allow wheel group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Prevent warning in sudo 1.8.31
      lineinfile:
        path: /etc/sudo.conf
        line: "Set disable_coredump false"
        create: yes

    - name: Create dst user
      user:
        name: dst
        password: "{{ 'dst' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: wheel
        append: true

    - name: Configure bash
      blockinfile:
        path: /home/dst/.bashrc
        block: |
          export PAGER="less"
          export PS1="\[\033[38;5;6m\][\w]$\[$(tput sgr0)\] "
          export PATH="/usr/bin/dsutils:${PATH}"

    - name: Ensure .bash_aliases exists
      file:
        path: /home/dst/.bash_aliases
        state: touch
        owner: dst
        group: dst

    - name: Add bash aliases
      blockinfile:
        path: /home/dst/.bash_aliases
        block: |
          alias l="ls -lhF --group-directories-first"
          alias parallel="parallel --will-cite"
          alias python="python3"

    - name: Symlink python3
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - name: Install zsh
      apt:
        pkg:
         - zsh
         - locales

    - name: Ensure .zshrc exists
      file:
        path: /home/dst/.zshrc
        state: touch
        owner: dst
        group: dst

    - name: Install zsh syntax highlighting
      shell:
        cmd: mkdir -p /home/dst/.zsh/zsh-syntax-highlighting && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/dst/.zsh/zsh-syntax-highlighting && chown -R dst:dst /home/dst/.zsh

    - name: Add zshrc config
      blockinfile:
        path: /home/dst/.zshrc
        block: |
          autoload -U compinit
          compinit
          export PAGER="less"
          export PS1='%B$%b '
          export PS2='%B>%b '
          export PATH="/usr/local/lib/R/site-library/rush/exec:/usr/bin/dsutils:/home/dst/.local/bin:${PATH}"
          export LC_CTYPE=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          export HISTSAVE=1000000
          export EDITOR=nano
          export TZ="America/Toronto"
          alias l="ls --color -lhF --group-directories-first"
          alias parallel="parallel --will-cite"
          alias python="python3"
          source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

    - name: Make zsh default shell
      shell:
        cmd: chsh -s $(which zsh) dst

    - name: Set locale
      shell:
        cmd: locale-gen en_US.UTF-8

    - name: Empty tmp directory
      shell:
        cmd: rm -rf /tmp/*
        warn: false
